version: '3'

networks:
  hrm-net:

services:
  front-end:
    image: dtr.ucsbang6.com/admin/weaveworksdemos-front-end
    ports:
      - '82:8079'
    environment:
      - reschedule=on-node-failure
    networks:
      - hrm-net

  catalogue:
    image: dtr.ucsbang6.com/admin/weaveworksdemos-catalogue
    environment:
      - reschedule=on-node-failure
    networks:
      - hrm-net

  catalogue-db:
    image: dtr.ucsbang6.com/admin/weaveworksdemos-catalogue-db
    environment:
      - reschedule=on-node-failure
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_DATABASE=socksdb
    networks:
      - hrm-net

  carts:
    image: dtr.ucsbang6.com/admin/weaveworksdemos-carts
    environment:
      - reschedule=on-node-failure
      - JAVA_OPTS=-Xms64m -Xmx128m -XX:+UseG1GC -Djava.security.egd=file:/dev/urandom -Dspring.zipkin.enabled=false
    networks:
      - hrm-net

  carts-db:
    image: dtr.ucsbang6.com/admin/mongo
    environment:
      - reschedule=on-node-failure
    networks:
      - hrm-net

  orders:
    image: dtr.ucsbang6.com/admin/weaveworksdemos-orders
    environment:
      - reschedule=on-node-failure
      - JAVA_OPTS=-Xms64m -Xmx128m -XX:+UseG1GC -Djava.security.egd=file:/dev/urandom -Dspring.zipkin.enabled=false
    networks:
      - hrm-net

  orders-db:
    image: dtr.ucsbang6.com/admin/mongo
    environment:
      - reschedule=on-node-failure
    networks:
      - hrm-net

  shipping:
    image: dtr.ucsbang6.com/admin/weaveworksdemos-shipping
    environment:
      - reschedule=on-node-failure
      - JAVA_OPTS=-Xms64m -Xmx128m -XX:+UseG1GC -Djava.security.egd=file:/dev/urandom -Dspring.zipkin.enabled=false
    networks:
      - hrm-net

  # @pidster: I've added this back in a comment, because I don't know why it is missing from this file
  # queue-master:
  #   image: weaveworksdemos/queue-master:0.3.1
  #   hostname: queue-master
  #   volumes:
  #     - /var/run/docker.sock:/var/run/docker.sock
  #   dns: 172.17.0.1
  #   environment:
  #     - reschedule=on-node-failure
  rabbitmq:
    image: dtr.ucsbang6.com/admin/rabbitmq
    environment:
      - reschedule=on-node-failure
    networks:
      - hrm-net

  payment:
    image: dtr.ucsbang6.com/admin/weaveworksdemos-payment
    environment:
      - reschedule=on-node-failure
    networks:
      - hrm-net

  user:
    image: dtr.ucsbang6.com/admin/weaveworksdemos-user
    environment:
      - MONGO_HOST=user-db:27017
      - reschedule=on-node-failure
    networks:
      - hrm-net

  user-db:
    image: dtr.ucsbang6.com/admin/weaveworksdemos-user-db
    environment:
      - reschedule=on-node-failure
    networks:
      - hrm-net
  user-sim:
    image: weaveworksdemos/load-test:0.1.1
    command: "-d 60 -r 200 -c 2 -h front-end:8079"
    networks:
      - hrm-net
