version: '3'

networks:
  hrm-net:

services:
  front-end:
    image: dtr.ucsbang6.com/admin/front-end:1
    #image: dtr.ucsbang6.com/admin/front-endd:2

    #image: weaveworksdemos/front-end:0.3.12
    ports:
      - '82:8079'
    environment:
      - reschedule=on-node-failure
    networks:
      - hrm-net

  catalogue:
    image: dtr.ucsbang6.com/admin/catalogue:1
    #image: dtr.ucsbang6.com/admin/cataloguee:2

    #image: weaveworksdemos/catalogue:0.3.5
    environment:
      - reschedule=on-node-failure
    networks:
      - hrm-net

  catalogue-db:
#    image: dtr.ucsbang6.com/admin/weaveworksdemos-catalogue-db:0.3.0
    image: weaveworksdemos/catalogue-db:0.3.0
    environment:
      - reschedule=on-node-failure
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_DATABASE=socksdb
    networks:
      - hrm-net
#    volumes:
#      - /mnt/catalogue-db:/docker-entrypoint-initdb.d

  carts:
#    image: dtr.ucsbang6.com/admin/weaveworksdemos-carts:0.4.8
    image: weaveworksdemos/carts:0.4.8
    environment:
      - reschedule=on-node-failure
      - JAVA_OPTS=-Xms64m -Xmx128m -XX:+UseG1GC -Djava.security.egd=file:/dev/urandom -Dspring.zipkin.enabled=false
    networks:
      - hrm-net

  carts-db:
#    image: dtr.ucsbang6.com/admin/mongo:3.4
    image: mongo:3.4
    environment:
      - reschedule=on-node-failure
    networks:
      - hrm-net
#    volumes:
#      - /mnt/carts-db:/data

  orders:
    image: weaveworksdemos/orders:0.4.7
    environment:
      - reschedule=on-node-failure
      - JAVA_OPTS=-Xms64m -Xmx128m -XX:+UseG1GC -Djava.security.egd=file:/dev/urandom -Dspring.zipkin.enabled=false
    networks:
      - hrm-net

  orders-db:
    image: mongo:3.4
    environment:
      - reschedule=on-node-failure
    networks:
      - hrm-net
#    volumes:
#      - /mnt/orders-db:/data

  shipping:
    image: weaveworksdemos/shipping:0.4.8
    environment:
      - reschedule=on-node-failure
      - JAVA_OPTS=-Xms64m -Xmx128m -XX:+UseG1GC -Djava.security.egd=file:/dev/urandom -Dspring.zipkin.enabled=false
    networks:
      - hrm-net

  rabbitmq:
    image: rabbitmq:3.6.8
    environment:
      - reschedule=on-node-failure
    networks:
      - hrm-net

  payment:
    image: weaveworksdemos/payment:latest
    environment:
      - reschedule=on-node-failure
    networks:
      - hrm-net

  user:
    image: weaveworksdemos/user-db:0.4.4
    environment:
      - MONGO_HOST=user-db:27017
      - reschedule=on-node-failure
    networks:
      - hrm-net

  user-db:
    image: mongo:3.4
    #image: dtr.ucsbang6.com/admin/mysql
    environment:
      - reschedule=on-node-failure
    networks:
      - hrm-net
    volumes:
      - /mnt:/data/db-users

  user-sim:
    image: weaveworksdemos/load-test:0.1.1
    command: "-d 60 -r 200 -c 2 -h front-end:8079"
    networks:
      - hrm-net
